#!/usr/bin/env python3
"""
B-SDD Standardized Skills Unpacker & Validator Harness.
100% Pure Python Standard Library (ADR-002 Compliance).
Reads a standardized corpus text file generated by Gemini Spark, parses delimited
skill blocks (=== BSSD_STANDARDIZED_SKILL_START: <name> ===), validates JSON schema
and planar graph topology (ADR-008, ADR-015, ADR-016), writes files directly into
~/.agents/skills/<name>/ and repo mirrors, and executes automated verification.
"""
import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

USER_SKILLS_DIR = Path(os.path.expanduser("~/.agents/skills")).resolve()
REPO_SKILLS_DIR = Path("/home/vokov/projects/b-sdd/.agents/skills").resolve()

VALID_NODE_TYPES = {"headline", "action", "question", "insertion", "end", "branch"}


def parse_skill_corpus(file_path: Path) -> List[Dict[str, Any]]:
    """Parses delimited skill blocks from the corpus file."""
    text = file_path.read_text(encoding="utf-8", errors="replace")
    pattern = re.compile(
        r"===\s*BSSD_STANDARDIZED_SKILL_START:\s*([a-zA-Z0-9_\-\.]+)\s*===(.*?)"
        r"===\s*BSSD_STANDARDIZED_SKILL_END:\s*\1\s*===",
        re.DOTALL
    )

    parsed_skills: List[Dict[str, Any]] = []
    for match in pattern.finditer(text):
        skill_name = match.group(1).strip()
        body = match.group(2)

        # Extract SKILL.md
        skill_md_match = re.search(
            r"---\s*FILE:\s*SKILL\.md\s*---(.*?)(?=---\s*FILE:|$)",
            body,
            re.DOTALL
        )
        # Extract <skill_name>.drakon.json
        drakon_json_match = re.search(
            r"---\s*FILE:\s*([a-zA-Z0-9_\-\.]+\.drakon\.json)\s*---(.*?)$",
            body,
            re.DOTALL
        )

        skill_md = skill_md_match.group(1).strip() if skill_md_match else ""
        drakon_raw = drakon_json_match.group(2).strip() if drakon_json_match else ""

        # Remove possible markdown code block fences (```json ... ```)
        if drakon_raw.startswith("```"):
            lines = drakon_raw.splitlines()
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            drakon_raw = "\n".join(lines).strip()

        parsed_skills.append({
            "name": skill_name,
            "skill_md": skill_md,
            "drakon_raw": drakon_raw,
        })

    return parsed_skills


def validate_drakon_schema(skill_name: str, drakon_data: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """Validates DRAKON IR schema and planar skewer topology."""
    errors: List[str] = []

    if not isinstance(drakon_data, dict):
        return False, ["Root is not a JSON object"]

    nodes = drakon_data.get("nodes")
    if not isinstance(nodes, list) or len(nodes) == 0:
        return False, ["Missing or empty 'nodes' list"]

    node_ids: Set[str] = set()
    for idx, node in enumerate(nodes):
        if not isinstance(node, dict):
            errors.append(f"Node #{idx} is not an object")
            continue
        nid = node.get("node_id")
        if not nid:
            errors.append(f"Node #{idx} missing 'node_id'")
        elif nid in node_ids:
            errors.append(f"Duplicate node_id '{nid}'")
        else:
            node_ids.add(nid)

        ntype = node.get("node_type")
        if ntype not in VALID_NODE_TYPES:
            errors.append(f"Node '{nid}' has invalid node_type '{ntype}'")

        # Edge checks
        edges = node.get("edges", {})
        if not isinstance(edges, dict):
            errors.append(f"Node '{nid}' edges is not a dict")

        # Planar skewer check: x coordinate should be float
        x = node.get("x", 0.0)
        if not isinstance(x, (int, float)):
            errors.append(f"Node '{nid}' invalid x coordinate '{x}'")

    # Validate edge references exist
    for node in nodes:
        nid = node.get("node_id")
        edges = node.get("edges", {})
        for edge_key in ("down", "right"):
            target = edges.get(edge_key)
            if target and target not in node_ids:
                errors.append(f"Node '{nid}' edge '{edge_key}' points to non-existent node '{target}'")

    return len(errors) == 0, errors


def normalize_skill_md(skill_name: str, text: str) -> str:
    """Normalizes SKILL.md into canonical ADR-015/016 markdown format."""
    text = text.strip()

    # 1. Ensure YAML frontmatter is delimited by '---'
    if not text.startswith("---"):
        lines = text.splitlines()
        fm_lines = ["---"]
        in_fm = True
        body_lines = []
        for line in lines:
            s = line.strip()
            if in_fm:
                if any(s.startswith(k) for k in ("name:", "description:", "type:", "category:", "immutable:", "invoked_skills:")) or (s.startswith("- ") and fm_lines[-1].startswith("invoked_skills:")) or s == "":
                    if s:
                        fm_lines.append(s)
                else:
                    in_fm = False
                    fm_lines.append("---")
                    body_lines.append(line)
            else:
                body_lines.append(line)
        if in_fm:
            fm_lines.append("---")
        text = "\n".join(fm_lines) + "\n\n" + "\n".join(body_lines)

    # 2. Ensure title is properly formatted with '#'
    lines = text.splitlines()
    new_lines = []
    fm_count = 0
    after_fm = False
    title_added = False
    for line in lines:
        if line.strip() == "---":
            fm_count += 1
            new_lines.append(line)
            if fm_count == 2:
                after_fm = True
            continue
        if after_fm and not title_added:
            s = line.strip()
            if s and not s.startswith("#") and not s.startswith("-"):
                new_lines.append(f"# {s}")
                title_added = True
                continue
            elif s.startswith("#"):
                title_added = True
        new_lines.append(line)
    text = "\n".join(new_lines)

    # 3. Ensure DRAKON visual anchor tags are present
    if "<!-- DRAKON_VISUAL_FLOW_START -->" not in text:
        m = re.search(r'((?:##\s*|\d+\.\s*)DRAKON Visual Workflow[^\n]*\n)(.*?)(\n-+\s*\n\s*(?:##\s*|\d+\.\s*)Operational Guide|\n(?:##\s*|\d+\.\s*)Operational Guide|$)', text, re.DOTALL | re.IGNORECASE)
        if m:
            heading = m.group(1).strip()
            if not heading.startswith("##"):
                heading = f"## {heading}"
            content = m.group(2).strip()
            rest = m.group(3) if m.group(3) else ""
            anchor_block = f"<!-- DRAKON_VISUAL_FLOW_START -->\n{heading}\n{content}\n<!-- DRAKON_VISUAL_FLOW_END -->"
            text = text[:m.start()] + anchor_block + "\n\n---\n\n" + rest.lstrip("-\n ") + text[m.end():]

    return text.strip() + "\n"


def validate_skill_md(skill_name: str, skill_md: str) -> Tuple[bool, List[str]]:
    """Validates that SKILL.md contains frontmatter and ALGORITHM pseudocode."""
    errors: List[str] = []
    if not skill_md.startswith("---"):
        errors.append("Missing opening YAML frontmatter '---'")

    if "ALGORITHM" not in skill_md:
        errors.append("Missing 'ALGORITHM <Name>' pseudocode block (ADR-016 Invariant)")

    if "<!-- DRAKON_VISUAL_FLOW_START -->" not in skill_md:
        errors.append("Missing '<!-- DRAKON_VISUAL_FLOW_START -->' visual anchor")

    return len(errors) == 0, errors


def unpack_skills(corpus_file: Path, dry_run: bool = False) -> Dict[str, Any]:
    skills = parse_skill_corpus(corpus_file)
    print(f"📦 Parsed {len(skills)} skill blocks from {corpus_file.name}")

    results = {
        "total": len(skills),
        "valid": 0,
        "failed": 0,
        "errors": {},
    }

    for skill in skills:
        name = skill["name"]
        skill_md = normalize_skill_md(name, skill["skill_md"])
        drakon_raw = skill["drakon_raw"]

        skill_errors: List[str] = []

        # Validate Markdown
        md_ok, md_errs = validate_skill_md(name, skill_md)
        if not md_ok:
            skill_errors.extend(md_errs)

        # Validate JSON
        drakon_data = None
        try:
            drakon_data = json.loads(drakon_raw)
            json_ok, json_errs = validate_drakon_schema(name, drakon_data)
            if not json_ok:
                skill_errors.extend(json_errs)
        except json.JSONDecodeError as je:
            skill_errors.append(f"Invalid JSON: {je}")

        if skill_errors:
            results["failed"] += 1
            results["errors"][name] = skill_errors
            print(f"❌ [{name}] Validation failed ({len(skill_errors)} errors): {skill_errors[0]}")
            continue

        results["valid"] += 1
        print(f"✓ [{name}] Validated successfully: {len(drakon_data['nodes'])} nodes, ADR-016 compliant.")

        if not dry_run:
            # Write to ~/.agents/skills/<name>/
            target_user_dir = USER_SKILLS_DIR / name
            target_user_dir.mkdir(parents=True, exist_ok=True)
            (target_user_dir / "SKILL.md").write_text(skill_md + "\n", encoding="utf-8")
            (target_user_dir / f"{name}.drakon.json").write_text(json.dumps(drakon_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

            # Write to repo mirror
            target_repo_dir = REPO_SKILLS_DIR / name
            target_repo_dir.mkdir(parents=True, exist_ok=True)
            (target_repo_dir / "SKILL.md").write_text(skill_md + "\n", encoding="utf-8")
            (target_repo_dir / f"{name}.drakon.json").write_text(json.dumps(drakon_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    return results


def main():
    parser = argparse.ArgumentParser(description="Unpack and validate Gemini Spark standardized skills corpus")
    parser.add_argument("corpus_file", type=str, help="Path to standardized_skills_corpus.txt")
    parser.add_argument("--dry-run", action="store_true", help="Validate without writing files to disk")
    args = parser.parse_args()

    corpus_path = Path(args.corpus_file).resolve()
    if not corpus_path.exists():
        print(f"❌ Error: File not found: {corpus_path}", file=sys.stderr)
        sys.exit(1)

    print(f"🚀 Unpacking standardized skills corpus from: {corpus_path}")
    res = unpack_skills(corpus_path, dry_run=args.dry_run)
    print(f"\n{'='*70}")
    print(f"📊 SUMMARY: Total={res['total']} | Valid={res['valid']} | Failed={res['failed']}")
    print(f"{'='*70}")

    if res["failed"] > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
